---
title: "First day of class!"
date: "2023-06-05T00:07"
categories: [getting started]
---

Hi everyone!

Today's the first day of class, and I'm excited to get started!

A few quick reminders:

- If you haven't yet, please visit the class website at <https://datavizs23.classes.andrewheiss.com/>. This is where all the class materials live and it's the official source of dates and all other class information. I only use iCollege for collecting your assignments and posting answer keys (since it's password protected). Because it's not part of iCollege, you'll be able to reference it even after you graduate and lose access to GSU resources. You can even share it with others—it's just a website! (In the past I've had students spend like an hour downloading all the content from the class website so they can keep it; don't worry about that though—it'll all stay there indefinitely!)

- As you'll see on the syllabus and schedule pages, the class is divided into 15 sessions (corresponding to a typical 15-week semester). Since this is a summer class, we're covering two sessions a week. You'll follow this general process for each session:

	1. Go to the content page, read the readings, and watch the slides/lectures
	2. Go to the lesson page and do the lessons
	3. Do the assignment, referring to the example page as you go

- [As you'll read here](/syllabus.qmd#r-and-rstudio), we're using R and RStudio in this class. You can use a neat service called Posit.cloud to get started (join the class workspace here using the link I sent via e-mail), but eventually you'll want to have R and RStudio on your computer. [Follow the instructions here](/resource/install.qmd) to do that

- If you haven't already, join the class Slack workspace at using the link I sent via e-mail. This is the best and fastest place to get help and talk to me and your classmates during the semester. I’ll also post general tips and tricks and advice there, so check it regularly.

- In addition to the lessons, examples, and assignments, [I've included a bunch of extra resources on the class website](/resource/index.qmd) - check out those different pages for extra links to things about graphic design, data visualization, R, R best practices, data, and lots of other things.

Cool cool cool, let's go!
